### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by georgii11** [sinaweibosdk/weibo_android_sdk#526]
Hello,

Is there a version with Android X support? Or is it in plan for a future release?

Thanks!

**Comment by lcdlyxrqy** [comment]
This is actually not a problem. You can force all the third-party libraries to use androidx libraries instead of legacy android support libraries by setting
```gradle
android.enableJetifier=true
```
Android Plugin will take care of the rest.
See [AndroidX Overview](https://developer.android.com/jetpack/androidx#using_androidx_libraries_in_your_project) for more information.
